### PR TITLE
Fixed waitDisappear

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@alex-deaconu please review. cheers

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi LG :+1: . 

I'm just trying to get an idea of where this would be used. I'm assuming for modals or page changes? What if the element is no longer present? Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu I am using it for the loading as when loading is running the elements under it cannot be accessed or are not present. I cannot think of any other use case, maybe there is but I guess we can change when we need it. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi got it. I was way off then! Sounds good, thanks for the additional info.

**Comment by olegrise** [comment]
Good simplification!

**Pull request merged**
