### PR TITLE
Remove resizing and log comparison to stdout

### PR DESCRIPTION
**Pull request by tejohnso**
@fjvallarino @ezequielc please review

### CODE REVIEW

**Comment by fjvallarino** [comment]
@tejohnso I'm not sure removing the resizing part is a good idea. When comparing different sized images, the compare script looks for the smallest "similar" image inside the bigger one, and it can be pretty slow (depending on the size of the images).

**Comment by tejohnso** [comment]
@fjvallarino from what I've seen compare will throw an error if the the images are of a different size.
>compare: image widths or heights differ

Thing is, there's no reason to provide an unmatched image size and then mogrify them.  We can generate the screenshots the same way they're generated on circle using xvfb

**Comment by fjvallarino** [comment]
@tejohnso wasn't that the problem we've always had with the e2e machines? That for some reason the machine's resolution would change and render the md5 hash invalid (because the image size also changed)?

**Comment by tejohnso** [comment]
@fjvallarino That was the thought, we never did prove that it was a resolution problem.  But that was a different mechanism, using an external screenshot tool against the output of a physical display that is configured via the OS (and changed with os updates).  This is now in a virtual framebuffer, and so far seems much more stable.  We can always add the resizing back in if it proves to be necessary.  From what I've seen, I'm thinking of going even further the other way and fail unless the comparison matches 100%.   I'll wait to see some additional circle-ci testing though.

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
